// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qouhfdjmlzrzuguycfra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdWhmZGptbHpyenVndXljZnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTQ5NzQsImV4cCI6MjA2MTk3MDk3NH0.PH6yDzsOz0pV92OPT-3UtU-bIdYFvM2NJQgQgufOiKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);